#!/bin/bash

function createmanufacturer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/manufacturer.agri.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/manufacturer.agri.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-manufacturer --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-manufacturer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-manufacturer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-manufacturer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-manufacturer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy manufacturer's CA cert to manufacturer's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/msp/tlscacerts/ca.crt"

  # Copy manufacturer's CA cert to manufacturer's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/tlsca/tlsca.manufacturer.agri.com-cert.pem"

  # Copy manufacturer's CA cert to manufacturer's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/ca"
  cp "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/ca/ca.manufacturer.agri.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-manufacturer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-manufacturer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-manufacturer --id.name manufactureradmin --id.secret manufactureradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/peers/peer0.manufacturer.agri.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/peers/peer0.manufacturer.agri.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/peers/peer0.manufacturer.agri.com/tls" --enrollment.profile tls --csr.hosts peer0.manufacturer.agri.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/peers/peer0.manufacturer.agri.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/peers/peer0.manufacturer.agri.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/peers/peer0.manufacturer.agri.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/peers/peer0.manufacturer.agri.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/peers/peer0.manufacturer.agri.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/peers/peer0.manufacturer.agri.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/users/User1@manufacturer.agri.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/users/User1@manufacturer.agri.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://manufactureradmin:manufactureradminpw@localhost:7054 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/users/Admin@manufacturer.agri.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/manufacturer.agri.com/users/Admin@manufacturer.agri.com/msp/config.yaml"
}

function createverifier() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/verifier.agri.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/verifier.agri.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:10054 --caname ca-verifier --tls.certfiles "${PWD}/organizations/fabric-ca/verifier/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-verifier.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-verifier.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-verifier.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-verifier.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/verifier.agri.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy verifier's CA cert to verifier's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/verifier.agri.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/verifier/ca-cert.pem" "${PWD}/organizations/peerOrganizations/verifier.agri.com/msp/tlscacerts/ca.crt"

  # Copy verifier's CA cert to verifier's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/verifier.agri.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/verifier/ca-cert.pem" "${PWD}/organizations/peerOrganizations/verifier.agri.com/tlsca/tlsca.verifier.agri.com-cert.pem"

  # Copy verifier's CA cert to verifier's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/verifier.agri.com/ca"
  cp "${PWD}/organizations/fabric-ca/verifier/ca-cert.pem" "${PWD}/organizations/peerOrganizations/verifier.agri.com/ca/ca.verifier.agri.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-verifier --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/verifier/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-verifier --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/verifier/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-verifier --id.name verifieradmin --id.secret verifieradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/verifier/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-verifier -M "${PWD}/organizations/peerOrganizations/verifier.agri.com/peers/peer0.verifier.agri.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/verifier/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/verifier.agri.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/verifier.agri.com/peers/peer0.verifier.agri.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-verifier -M "${PWD}/organizations/peerOrganizations/verifier.agri.com/peers/peer0.verifier.agri.com/tls" --enrollment.profile tls --csr.hosts peer0.verifier.agri.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/verifier/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/verifier.agri.com/peers/peer0.verifier.agri.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/verifier.agri.com/peers/peer0.verifier.agri.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/verifier.agri.com/peers/peer0.verifier.agri.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/verifier.agri.com/peers/peer0.verifier.agri.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/verifier.agri.com/peers/peer0.verifier.agri.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/verifier.agri.com/peers/peer0.verifier.agri.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:10054 --caname ca-verifier -M "${PWD}/organizations/peerOrganizations/verifier.agri.com/users/User1@verifier.agri.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/verifier/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/verifier.agri.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/verifier.agri.com/users/User1@verifier.agri.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://verifieradmin:verifieradminpw@localhost:10054 --caname ca-verifier -M "${PWD}/organizations/peerOrganizations/verifier.agri.com/users/Admin@verifier.agri.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/verifier/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/verifier.agri.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/verifier.agri.com/users/Admin@verifier.agri.com/msp/config.yaml"
}

function createdealer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/dealer.agri.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/dealer.agri.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-dealer --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-dealer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-dealer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-dealer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-dealer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/dealer.agri.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy dealer's CA cert to dealer's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/dealer.agri.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/dealer.agri.com/msp/tlscacerts/ca.crt"

  # Copy dealer's CA cert to dealer's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/dealer.agri.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/dealer.agri.com/tlsca/tlsca.dealer.agri.com-cert.pem"

  # Copy dealer's CA cert to dealer's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/dealer.agri.com/ca"
  cp "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/dealer.agri.com/ca/ca.dealer.agri.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-dealer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering peer1"
  set -x
  fabric-ca-client register --caname ca-dealer --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-dealer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-dealer --id.name dealeradmin --id.secret dealeradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-dealer -M "${PWD}/organizations/peerOrganizations/dealer.agri.com/peers/peer0.dealer.agri.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/dealer.agri.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/dealer.agri.com/peers/peer0.dealer.agri.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-dealer -M "${PWD}/organizations/peerOrganizations/dealer.agri.com/peers/peer0.dealer.agri.com/tls" --enrollment.profile tls --csr.hosts peer0.dealer.agri.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/dealer.agri.com/peers/peer0.dealer.agri.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/dealer.agri.com/peers/peer0.dealer.agri.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/dealer.agri.com/peers/peer0.dealer.agri.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/dealer.agri.com/peers/peer0.dealer.agri.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/dealer.agri.com/peers/peer0.dealer.agri.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/dealer.agri.com/peers/peer0.dealer.agri.com/tls/server.key"

    echo "Generating the peer1 msp"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:8054 --caname ca-dealer -M "${PWD}/organizations/peerOrganizations/dealer.agri.com/peers/peer1.dealer.agri.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/dealer.agri.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/dealer.agri.com/peers/peer1.dealer.agri.com/msp/config.yaml"

  echo "Generating the peer1-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:8054 --caname ca-dealer -M "${PWD}/organizations/peerOrganizations/dealer.agri.com/peers/peer1.dealer.agri.com/tls" --enrollment.profile tls --csr.hosts peer1.dealer.agri.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/dealer.agri.com/peers/peer1.dealer.agri.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/dealer.agri.com/peers/peer1.dealer.agri.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/dealer.agri.com/peers/peer1.dealer.agri.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/dealer.agri.com/peers/peer1.dealer.agri.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/dealer.agri.com/peers/peer1.dealer.agri.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/dealer.agri.com/peers/peer1.dealer.agri.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-dealer -M "${PWD}/organizations/peerOrganizations/dealer.agri.com/users/User1@dealer.agri.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/dealer.agri.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/dealer.agri.com/users/User1@dealer.agri.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://dealeradmin:dealeradminpw@localhost:8054 --caname ca-dealer -M "${PWD}/organizations/peerOrganizations/dealer.agri.com/users/Admin@dealer.agri.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/dealer.agri.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/dealer.agri.com/users/Admin@dealer.agri.com/msp/config.yaml"
}

#!/bin/bash

function createbuyer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/buyer.agri.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/buyer.agri.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-buyer --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-buyer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-buyer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-buyer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-buyer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/buyer.agri.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy buyer's CA cert to buyer's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/buyer.agri.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/buyer.agri.com/msp/tlscacerts/ca.crt"

  # Copy buyer's CA cert to buyer's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/buyer.agri.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/buyer.agri.com/tlsca/tlsca.buyer.agri.com-cert.pem"

  # Copy buyer's CA cert to buyer's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/buyer.agri.com/ca"
  cp "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/buyer.agri.com/ca/ca.buyer.agri.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-buyer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-buyer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-buyer --id.name buyeradmin --id.secret buyeradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-buyer -M "${PWD}/organizations/peerOrganizations/buyer.agri.com/peers/peer0.buyer.agri.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/buyer.agri.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/buyer.agri.com/peers/peer0.buyer.agri.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-buyer -M "${PWD}/organizations/peerOrganizations/buyer.agri.com/peers/peer0.buyer.agri.com/tls" --enrollment.profile tls --csr.hosts peer0.buyer.agri.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/buyer.agri.com/peers/peer0.buyer.agri.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/buyer.agri.com/peers/peer0.buyer.agri.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/buyer.agri.com/peers/peer0.buyer.agri.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/buyer.agri.com/peers/peer0.buyer.agri.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/buyer.agri.com/peers/peer0.buyer.agri.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/buyer.agri.com/peers/peer0.buyer.agri.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-buyer -M "${PWD}/organizations/peerOrganizations/buyer.agri.com/users/User1@buyer.agri.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/buyer.agri.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/buyer.agri.com/users/User1@buyer.agri.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://buyeradmin:buyeradminpw@localhost:11054 --caname ca-buyer -M "${PWD}/organizations/peerOrganizations/buyer.agri.com/users/Admin@buyer.agri.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/buyer.agri.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/buyer.agri.com/users/Admin@buyer.agri.com/msp/config.yaml"
}


function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/agri.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/agri.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/agri.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/agri.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/agri.com/msp/tlscacerts/tlsca.agri.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/agri.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/agri.com/tlsca/tlsca.agri.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/agri.com/orderers/orderer.agri.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/agri.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/agri.com/orderers/orderer.agri.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/agri.com/orderers/orderer.agri.com/tls" --enrollment.profile tls --csr.hosts orderer.agri.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/agri.com/orderers/orderer.agri.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/agri.com/orderers/orderer.agri.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/agri.com/orderers/orderer.agri.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/agri.com/orderers/orderer.agri.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/agri.com/orderers/orderer.agri.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/agri.com/orderers/orderer.agri.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/agri.com/orderers/orderer.agri.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/agri.com/orderers/orderer.agri.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/agri.com/orderers/orderer.agri.com/msp/tlscacerts/tlsca.agri.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/agri.com/users/Admin@agri.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/agri.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/agri.com/users/Admin@agri.com/msp/config.yaml"
}

createmanufacturer
createverifier
createdealer
createbuyer
createOrderer